// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: 'http://localhost:8080' | (string & {});
};

export type SignUpRequestDto = {
	firstName?: string;
	middleName?: string;
	lastName?: string;
	email?: string;
	password?: string;
};

export type AuthResponseDto = {
	token?: string;
	expiresIn?: number;
};

export type SignInRequestDto = {
	email?: string;
	password?: string;
};

export type SignUpData = {
	body: SignUpRequestDto;
	path?: never;
	query?: never;
	url: '/auth/signup';
};

export type SignUpResponses = {
	/**
	 * OK
	 */
	200: AuthResponseDto;
};

export type SignUpResponse = SignUpResponses[keyof SignUpResponses];

export type SignInData = {
	body: SignInRequestDto;
	path?: never;
	query?: never;
	url: '/auth/signin';
};

export type SignInResponses = {
	/**
	 * OK
	 */
	200: AuthResponseDto;
};

export type SignInResponse = SignInResponses[keyof SignInResponses];
