// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: 'http://localhost:8080' | (string & {});
};

/**
 * Standard error structure
 */
export type ErrorResponse = {
	message: string;
};

export type SignUpRequestDto = {
	firstName: string;
	middleName: string;
	lastName: string;
	email: string;
	password: string;
};

export type Unit = {
	[key: string]: unknown;
};

export type SignInRequestDto = {
	email: string;
	password: string;
	rememberMe: boolean;
};

export type SignUpData = {
	body: SignUpRequestDto;
	path?: never;
	query?: never;
	url: '/auth/signup';
};

export type SignUpErrors = {
	/**
	 * Bad Request
	 */
	400: ErrorResponse;
};

export type SignUpError = SignUpErrors[keyof SignUpErrors];

export type SignUpResponses = {
	/**
	 * OK
	 */
	200: Unit;
};

export type SignUpResponse = SignUpResponses[keyof SignUpResponses];

export type SignInData = {
	body: SignInRequestDto;
	path?: never;
	query?: never;
	url: '/auth/signin';
};

export type SignInErrors = {
	/**
	 * Bad Request
	 */
	400: ErrorResponse;
};

export type SignInError = SignInErrors[keyof SignInErrors];

export type SignInResponses = {
	/**
	 * OK
	 */
	200: Unit;
};

export type SignInResponse = SignInResponses[keyof SignInResponses];
